//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EelData.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trigger
    {
        public int BassinID { get; set; }
        public int WarningID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        public virtual Bassin Bassin { get; set; }
        public virtual Warning Warning { get; set; }
    }
}
